name: bootjack_example_app
description: A web app example for bootjack.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bootjack:
    path: ../

dev_dependencies:
  build_runner: ^2.4.1
  build_test: ^2.1.7
  build_web_compilers: ^4.0.3
