name: bootjack
version: 3.0.0+1
description: Bootjack is a porting of Twitter Bootstrap 3.0.x in Dart.
homepage: https://github.com/rikulo/bootjack
documentation: https://pub.dev/documentation/bootjack/latest/
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  dquery: any
