name: bootjack
version: 1.0.1
description: Bootjack is a porting of Twitter Bootstrap 3.0.x in Dart.
homepage: https://github.com/rikulo/bootjack
documentation: http://blog.rikulo.org/posts/2013/May/General/bootjack-and-dquery/ 
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  dquery: any
